# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: infra-pipeline

on: 
  push:  
    branches: [ main ]
    paths: 
      - 'terraform/main_infra/**'
  
  workflow_dispatch:  

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/main_infra

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: create tfvars file
        run: printf '%s' "${{ secrets.TF_VARS }}" > terraform.tfvars

      - name: Check tfvars real content
        run: cat -n terraform.tfvars  

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan -out=tfplan 

      - name: terraform apply
        run: terraform apply -auto-approve tfplan
 
      
